# Generated by Django 2.1.2 on 2018-10-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('isbn', models.CharField(blank='', max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=15)),
                ('publisher', models.CharField(blank='', max_length=30)),
                ('publication_date', models.DateField(blank='', null=True)),
                ('link', models.CharField(max_length=100)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Book.Topic'),
        ),
    ]
