# Generated by Django 2.1.2 on 2018-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank='', max_length=30, null=True),
        ),
    ]
