# Generated by Django 2.1.2 on 2018-10-01 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, default='', max_length=13)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=30)),
                ('favorite_books', models.ManyToManyField(related_name='user_fav_books', to='Book.Book')),
                ('reading_list', models.ManyToManyField(related_name='user_reading_list', to='Book.Book')),
            ],
        ),
    ]
